<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="9" hostname="DESKTOP-CS733UO" name="assertions.Hard_assertion" tests="10" failures="1" timestamp="15 Jul 2022 02:57:35 GMT" time="0.022" errors="0">
  <testcase name="Test10" time="0.022" classname="assertions.Hard_assertion">
    <failure type="java.lang.AssertionError" message="not same expected object to not be null">
      <![CDATA[java.lang.AssertionError: not same expected object to not be null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.assertNotNull(Assert.java:422)
	at assertions.Hard_assertion.Test10(Hard_assertion.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Test10 -->
  <testcase name="Test9" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test9 -->
  <testcase name="Test7" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test7 -->
  <testcase name="Test8" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test8 -->
  <testcase name="Test5" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test5 -->
  <testcase name="Test3" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test1" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test6" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test6 -->
  <testcase name="Test" classname="assertions.Hard_assertion">
    <skipped/>
  </testcase> <!-- Test -->
</testsuite> <!-- assertions.Hard_assertion -->
